core/urls.py
from django.urls import path
from core.views import home, no_permission
urlpatterns = [
    path('',home,name='home'),
    path('no_permission/',no_permission,name='no_permission')
]

task_management/urls.py
from django.contrib import admin
from django.urls import path,include
from tasks.views import dashboard
from debug_toolbar.toolbar import debug_toolbar_urls
from core.views import no_permission
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('core.urls')),
    path('tasks/',include('tasks.urls')), #adding urls of the tasks app
]+ debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks.views import manager_dashboard, dashboard, employee_dashboard
from tasks.views import create_task, view_task, update_task, delete_task, task_details
urlpatterns = [
    # path('dashboard/',dashboard),
    path('manager_dashboard/',manager_dashboard, name='manager_dashboard'),
    path('user_dashboard/',employee_dashboard, name='user_dashboard'),
    path('create_task/',create_task, name='create_task'),
    path('view_task/', view_task, name='view_task'),
    path('task_details/<int:task_id>/details/', task_details, name='task_details'),
    path('update_task/<int:id>/', update_task, name='update_task'),
    path('delete_task/<int:id>/', delete_task, name='delete_task'),
    path('dashboard/',dashboard,name='dashboard')    

]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
# class Employee(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.EmailField(unique=True)

#     def __str__(self):
#         return self.name


class Task(models.Model):
    PENDING='P'
    IN_PROGRESS='IP'
    COMPLETED='C'    
    STATUS_CHOICES = [
        (PENDING,'Pending'),
        (IN_PROGRESS,'In Progress'),
        (COMPLETED,'Completed')
    ]
    project = models.ForeignKey(
        'Project',
        on_delete=models.CASCADE,
        default=1,
        related_name="tasks"
        )
    assigned_to = models.ManyToManyField(
        # Employee,
        User,
        related_name='tasks'
        )
    title=models.CharField(max_length=250)
    description=models.TextField()
    due_date=models.DateField()
    status = models.CharField(max_length=15,choices=STATUS_CHOICES,default=PENDING)
    # is_completed=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    # taskDetails
    #Dunder method to return data
    def __str__(self):
        return f"Title: {self.title}, Status: {self.status}"

# one to one
class TaskDetail(models.Model):
    HIGH='H'
    MEDIUM='M'
    LOW='L'
    PRIORITY_OPTIONS=(
        (HIGH,'High'),
        (MEDIUM,'Medium'),
        (LOW,'Low')
    )
    # for work with images
    asset = models.ImageField(upload_to='tasks_asset', blank=True, null=True, default='tasks_asset/default_img.png')
    # assigned_to=models.CharField(max_length=250)
    priority=models.CharField(max_length=1,choices=PRIORITY_OPTIONS,default=LOW)
    # std_id = models.CharField(max_length=200, primary_key=True) # define customized primary key
    task=models.OneToOneField(
        Task,
        on_delete=models.CASCADE,
        related_name='taskDetails'
        )
    notes = models.TextField(blank=True, null=True)

    # Dunder method to return details of task title
    def __str__(self):
        return f"Details of {self.task.title}"
# many to many
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()

# Dunder Method
    def __str__(self):
        return self.name
# many to one
# task = one task is perform by many people
# employee = one employee perform too many task.

#

tasks/forms.py
from django import forms
from tasks.models import Task, TaskDetail

# Django Basic Form
# class TaskForm(forms.Form):
#     title = forms.CharField(max_length=250,label='Task Title')
#     description = forms.CharField(widget=forms.Textarea, label='Task Description')
#     due_date = forms.DateField(widget=forms.SelectDateWidget, label='Due Date')
#     assigned_to = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=[], label='Assigned To')


#     def __init__(self, *args, **kwargs):
#         # print(args,kwargs)
#         employees=kwargs.pop('employees',[])
#         print(employees)
#         super().__init__(*args, **kwargs)
#         self.fields['assigned_to'].choices=[(emp.id, emp.name) for emp in employees]

# Django FormModel

"""Form Mixing"""
class StyleFormMixing:

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.apply_styled_widgets()

    """ Mixing to apply style to Form field """
    default_classes = "w-full border-2 rounded-lg p-2"

    def apply_styled_widgets(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget,forms.TextInput):
                field.widget.attrs.update({
                    'class':self.default_classes,
                    'placeholder':f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget,forms.Textarea):
                field.widget.attrs.update({
                    'class': f"{self.default_classes} resize-none",
                    'placeholder': f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget,forms.SelectDateWidget):
                field.widget.attrs.update({
                    'class':"border-2 rounded-lg",
                    'placeholder':f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget,forms.CheckboxSelectMultiple):
                field.widget.attrs.update({
                    'class':"border-2 rounded-lg p-4",
                    'placeholder':f"Enter {field.label}"
                })
            else:
                field.widget.attrs.update({
                    'class': self.default_classes
                })


class TaskModelForm(StyleFormMixing, forms.ModelForm):
    class Meta:
        model = Task
        # fields = '__all__'
        fields = ['title','description','due_date','assigned_to'] #add 'assigned_to'
        # exclude = ['project','is_completed','created_at','updated_at']
        # define widgets which is not 
        widgets={
            'due_date':forms.SelectDateWidget,
            'assigned_to': forms.CheckboxSelectMultiple
        }
        """ Manual Widget"""
        # widgets={
        #     'title': forms.TextInput(attrs={
        #         'class':" w-full border-2 rounded-lg",
        #         'placeholder':"Enter Your Title"
        #     }),
        #     'description': forms.Textarea(attrs={
        #         'class':"w-full border-2 rounded-lg",
        #         'placeholder':'Give your task description'
        #     }),
        #     'due_date': forms.SelectDateWidget(attrs={
        #         'class':"border border-gray-300 rounded-md p-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        #     }),
        #     'assigned_to': forms.CheckboxSelectMultiple(attrs={
        #         'class':"mt-1 w-full text-blue-600 bg-white border-gray-300 rounded focus:ring-2 focus:ring-blue-500"
        #     })
        # } 


class TaskDetailModelForm(StyleFormMixing, forms.ModelForm):
    class Meta:
        model =  TaskDetail
        fields = ['priority','notes','asset']

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.forms import TaskModelForm, TaskDetailModelForm
from tasks.models import Task, TaskDetail, Project
from datetime import date
from django.db.models import Q, Count, Max, Min, Avg
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required
from django.contrib.auth.models import User
from users.views import is_admin
# Create your views here.

def is_Manager(user):
    return user.groups.filter(name='Manager').exists()

def is_Employee(user):
    return user.groups.filter(name='Employee').exists()


def dashboard(request):
    return render(request,'dashboard/dashboard.html')

@user_passes_test(is_Manager, login_url='no_permission')
def manager_dashboard(request):
    tasks = Task.objects.select_related('taskDetails').prefetch_related('assigned_to').all()
    # Getting task count
    # total_task = tasks.count()
    # completed_task = Task.objects.filter(status="COMPLETED").count()
    # in_progress_task = Task.objects.filter(status="IN_PROGRESS").count()
    # pending_task = Task.objects.filter(status="PENDING").count()

    counts = Task.objects.aggregate(
        total=Count('id'),
        completed = Count('id', filter=Q(status="COMPLETED")),
        in_progress = Count('id',filter=Q(status = "IN_PROGRESS")),
        pending = Count('id', filter=Q(status="PENDING"))
    )
    
    # Retrieve Data based on criteria

    # get data from the url
    type = request.GET.get('type','all')

    # base query
    base_query = Task.objects.select_related('taskDetails').prefetch_related('assigned_to')

    #condition to retrieve data by url type
    if type == "completed":
        tasks = base_query.filter(status="COMPLETED")
    elif type == "in_progress":
        tasks = base_query.filter(status="IN_PROGRESS")
    elif type == "pending":
        tasks = base_query.filter(status="PENDING")
    elif type == "all" :
        base_query.all()

    # print(tasks)

    context ={
        "tasks": tasks,
        "counts": counts
    }
    
    return render(request,'dashboard/manager_dashboard.html',context)

# CRUD
# C=CREATE
# R = READ
# U = UPDATE
# D = DELETE

@user_passes_test(is_Employee, login_url='no_permission')
def employee_dashboard(request):
    return render(request,'dashboard/user_dashboard.html')

@login_required
@permission_required('tasks.add_task', login_url = 'no_permission')
def create_task(request):
    employees=User.objects.all()
    task_form = TaskModelForm() # For GET
    task_detail_form = TaskDetailModelForm() # GET operation

    if request.method == 'POST':
        # form = TaskForm(request.POST, employees=employees) # For Django Basic Form POST
        task_form = TaskModelForm(request.POST) # For Django Model Form
        task_detail_form = TaskDetailModelForm(request.POST, request.FILES)
        if task_form.is_valid() and task_detail_form.is_valid():
            """ For Django Model Form """
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()
            messages.success(request,'Task Created Successfully')
            return redirect('create_task')
            # return render(request, 'test_form.html', {"task_form":task_form,"task_detail_form":task_detail_form,"message":"Data is successfully added"})
            """ For Django Basic Form  Data"""
            # data = form.cleaned_data
            # title = data.get('title')
            # description = data.get('description')
            # due_date = data.get('due_date')
            # assigned_to = data.get('assigned_to')

            # task=Task.objects.create(title=title, description=description, due_date=due_date)

            # # Assign employee to task
            # for emp_id in assigned_to:
            #     employee = Employee.objects.get(id=emp_id)
            #     task.assigned_to.add(employee)
            
            # return HttpResponse('Task Added Successfully')

    context={
        "task_form": task_form,
        "task_detail_form": task_detail_form
    }
    return render(request,'test_form.html',context)

@login_required
@permission_required('tasks.change_task', login_url='no_permission')
def update_task(request, id):
    # employees=Employee.objects.all()
    task = Task.objects.get(id=id)
    task_form = TaskModelForm(instance=task) # For GET
    if task.taskDetails:
        task_detail_form = TaskDetailModelForm(instance=task.taskDetails) # GET operation

    if request.method == 'POST':
        # form = TaskForm(request.POST, employees=employees) # For Django Basic Form POST
        task_form = TaskModelForm(request.POST, instance=task) # For Django Model Form
        task_detail_form = TaskDetailModelForm(request.POST, instance=task.taskDetails)
        if task_form.is_valid() and task_detail_form.is_valid():
            """ For Django Model Form """
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()
            messages.success(request,'Task Updated Successfully')
            return redirect('update_task',id)
            # return render(request, 'test_form.html', {"task_form":task_form,"task_detail_form":task_detail_form,"message":"Data is successfully added"})
            """ For Django Basic Form  Data"""
            # data = form.cleaned_data
            # title = data.get('title')
            # description = data.get('description')
            # due_date = data.get('due_date')
            # assigned_to = data.get('assigned_to')

            # task=Task.objects.create(title=title, description=description, due_date=due_date)

            # # Assign employee to task
            # for emp_id in assigned_to:
            #     employee = Employee.objects.get(id=emp_id)
            #     task.assigned_to.add(employee)
            
            # return HttpResponse('Task Added Successfully')

    context={
        "task_form": task_form,
        "task_detail_form": task_detail_form
    }
    return render(request,'test_form.html',context)

@login_required
@permission_required('tasks.delete_task', login_url='no_permission')
def delete_task(request, id):
    if request.method == "POST":
        task = Task.objects.get(id=id)
        task.delete()
        messages.success(request,"Task is deleted successfully")
        
        return redirect('manager_dashboard')

@login_required
@permission_required('tasks.view_task', login_url='no_permission')
def view_task(request):
    # Retrieve all data of Task model
    # tasks=Task.objects.all()

    # Retrieve specific data get by id
    # task_3=Task.objects.get(id=1)

    # Retrieve specific data get by first
    # task_4=Task.objects.first()

    # Retrieve task details by primary key (pk)
    # task_5 = Task.objects.get(pk=1)
    
    # return render (request,'show_task.html',{'tasks':tasks, 'task_3':task_3, 'task_4':task_4, 'task_5': task_5})

    # Get specific data by filtering
    # tasks=Task.objects.filter(status='PENDING')

    # show the task by
    # tasks = Task.objects.filter(due_date=date.today())

    """ Show the task which priority is not low"""
    # tasks=TaskDetail.objects.exclude(priority="L")

    """ Show the task which priority is not high"""
    # tasks=TaskDetail.objects.exclude(priority="H")

    """Show the task that contain word 'paper' and status PENDING """
    # tasks=Task.objects.filter(title__icontains = "p", status="PENDING")
    
    """Show the task that contains which are pending or in-progress"""
    # tasks=Task.objects.filter(Q(status="PENDING")|Q(status="IN_PROGRESS"))
    
    # tasks=Task.objects.filter(status="aldfjasldfk").exists()


    """ select__related (ForeignKey, OneToOneField)"""
    # tasks = Task.objects.all()
    # tasks = Task.objects.select_related('details').all()
    # tasks = TaskDetail.objects.select_related('task').all()
    # tasks = Task.objects.select_related('project').all()

    """ Prefetch__related. It's works for (Foreign Key, ManyToMany)"""
    # tasks = Project.objects.prefetch_related('projects').all()
    # return render(request,'show_task.html',{'tasks':tasks})

    """Aggregate Function"""
    # task_count = Task.objects.aggregate(num_task=Count('id'))
    # return render(request,'show_task.html',{'task_count':task_count})

    projects=Project.objects.annotate(num_task=Count('tasks')).order_by('num_task')
    return render(request,'show_task.html',{'projects':projects})

@login_required
@permission_required('tasks.view_task', login_url='no_permission')
def task_details(request, task_id):
    task = Task.objects.get(id=task_id)
    status_choices = Task.STATUS_CHOICES
    if request.method == 'POST':
        selected_status = request.POST.get('task_status')
        task.status = selected_status
        task.save()
        return redirect('task_details', task.id)
    return render(request, 'task_details.html',{'task':task, 'status_choices':status_choices})


# @login_required
# @permission_required('tasks.view_task',login_url='no_permission')
# def change_task(request):
@login_required
def dashboard(request):
    if is_Manager(request.user):
        return redirect('manager_dashboard')
    elif is_Employee(request.user):
        return redirect('user_dashboard')
    elif is_admin(request.user):
        return redirect('admin_dashboard')
    
    return redirect('no_permission')

tasks/templates/show_task.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "css/output.css" %}'>
    <title>Show Task</title>
</head>
<body>
    <div class="mx-auto p-10 w-9/10">
       {% comment %} <ul class="list-disc border-2">
            {% for project in tasks %}
            <li class="">
                {% for task in project.projects.all %}
                <div>{{task.title}}</div>
                {% endfor %}
            </li>
            {% endfor %}
        </ul>  {% endcomment %}
        {% comment %} <ul class="list-disc">
        {% for project in tasks %}
            <li><span class="text-xl font-weight-600">{{project.name}}</span>
            {% for project in project.projects.all %}
            <ul class="list-[upper-roman]">
            <li>{{project.title}}</li>
            </ul>
            {% endfor %}
            </li>
        {% endfor %}
        </ul> {% endcomment %}

        {% comment %} <p>{{task_count.num_task}}</p> {% endcomment %}
         <ul class="list-disc list-inside">
         {% for project in projects %}
         <li>
            <p><span>{{project.name}}</span>
            <span>{{project.num_task}}</span></p>
         </li>
         {% endfor %}
         </ul>
    </div>
</body>
</html>

tasks/templates/task_details.html
{% extends "base.html" %}
{% block title %}{{task.title|slice:":5"}}-Task Details{% endblock title %}
{% block content %}
<div class="container mx-auto px-4 py-8 max-w-10xl">
      <h1 class="text-3xl font-bold mb-6">{{task.title}}</h1>

      <!-- Navigation Tabs -->
      <div class="flex gap-4 mb-8 border-b">
        <button
          class="px-4 py-2 bg-blue-50 text-blue-600 rounded-t-lg flex items-center gap-2"
        >
          <svg
            class="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
            ></path>
          </svg>
          Task Detail
        </button>
        <div class="flex items-center gap-2">
          <form method="POST">
            {% csrf_token %}
          <select name="task_status" id="task_status" class="px-4 py-2 border rounded-md">
            {% for value, label in status_choices %}
                <option value="{{value}}">{{label}}</option>
            {% endfor %}
          </select>
          <button class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600" type="submit">
            Change Status
          </button>
          </form>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Main Content -->
        <div class="lg:col-span-2">
          <div class="bg-white p-6 rounded-lg shadow-sm">
            <!-- Status Tags -->
            <div class="flex gap-3 mb-6">
              <span
                class="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm"
                >{{task.taskDetails.get_priority_display|upper}} PRIORITY</span
              >
              <span
                class="px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm"
                >{{task.get_status_display|upper}}</span
              >
            </div>

            <!-- Creation Date -->
            <div class="text-gray-600 mb-6">Created At: {{task.created_at}}</div>

            <!-- Task Team -->
            <div class="mb-9">
              <h2 class="text-xl font-bold mb-4">TASK TEAM</h2>
              <div class="space-y-4">
                {% for emp in task.assigned_to.all %}
                    <div class="flex items-center gap-4">
                    <div class="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white">
                        {{emp.first_name|slice:":2"}}
                    </div>
                    <div>
                        <div class="font-semibold">{{emp.first_name}} {{emp.last_name}}</div>
                        <div class="text-gray-600">{{emp.groups.first.name}}</div>
                    </div>
                    </div>
                {% endfor %}
              </div>
            </div>
            <div class="flex justify-start items-center gap-2">
              <a href='{% url "update_task" task.id %}' class='px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600'>Edit</a>
                <form action="{% url "delete_task" task.id %}" method="POST">
                  {% csrf_token %}
                  <button class="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600" type="submit"> Delete Task </button>
                </form>
            </div>
          </div>
        </div>

        <!-- Sidebar -->
        <div class="lg:col-span-1">
          <!-- Task Description -->
          <div class="bg-white p-6 rounded-lg shadow-sm mb-6">
            <h2 class="text-xl font-bold mb-4">TASK DESCRIPTION</h2>
            <p class="text-gray-600">
              {{task.description}}
            </p>
          </div>

          <!-- Assets -->
          <div class="bg-white p-6 rounded-lg shadow-sm">
            <h2 class="text-xl font-bold mb-4">ASSETS</h2>
            <div class="space-y-4">
              <img
                src={{task.taskDetails.asset.url}}
                alt="Task Manager App Screenshot 1"
                class="w-full rounded-lg"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

tasks/templates/test_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/output.css" %}">
</head>
<body>
    <div class="w-1/2 mx-auto mt-8 border-2 rounded-xl bg-yellow-200 shadow-xl p-12">
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="px-2 py-1 {% if message.tags == 'success' %} bg-green-600 {% endif %}"> 
                    {{message}} 
                </div>
            {% endfor %}
            
        {% endif %}
    </div>
    <form method="POST" enctype = "multipart/form-data" >
        {% csrf_token %}
        {{ task_form}}
        {{task_detail_form}}
        <button type="submit" class="border-purple-200  hover:border-transparent hover:bg-purple-600 hover:text-white active:bg-purple-700 w-full border-2 rounded-lg shadow-xl bg-purple-400">Submit</button>
    </form>
    </div>
</body>
</html>